
<template>
<div class>

    <title-page title="Form Checkbox Inputs">
        <p class="bd-lead">For cross browser consistency, <code>&lt;b-form-checkbox-group&gt;</code> and <code>&lt;b-form-checkbox&gt;</code> use Bootstrap's
            custom checkbox input to replace the browser default checkbox input. It is built on top of
            semantic and accessible markup, so it is a solid replacement for the default checkbox input.</p>
    </title-page>

    <card-component>
        <b-form-checkbox id="checkbox-1"
            v-model="status"
            name="checkbox-1"
            value="accepted"
            unchecked-value="not_accepted">
            I accept the terms and use
        </b-form-checkbox>

        <div>State: <strong>{{ status }}</strong></div>
    </card-component>

    <title-page title="Multiple choice checkboxes">
        <p>Feel free to mix and match <code>options</code> prop and <code>&lt;b-form-checkbox&gt;</code> in <code>&lt;b-form-checkbox-group&gt;</code>.
            Manually placed <code>&lt;b-form-checkbox&gt;</code> inputs will appear <em>below</em> any checkbox inputs generated by the
            <code>options</code> prop. To have them appear <em>above</em> the inputs generated by <code>options</code>, place them in the
            named slot <code>first</code>.</p>
    </title-page>

    <card-component>
        <b-form-group label="Using options array:">
            <b-form-checkbox-group id="checkbox-group-1"
                v-model="selected"
                :options="options"
                name="flavour-1" />
        </b-form-group>

        <b-form-group label="Using sub-components:">
            <b-form-checkbox-group id="checkbox-group-2"
                v-model="selected"
                name="flavour-2">
                <b-form-checkbox value="orange">Orange</b-form-checkbox>
                <b-form-checkbox value="apple">Apple</b-form-checkbox>
                <b-form-checkbox value="pineapple">Pineapple</b-form-checkbox>
                <b-form-checkbox value="grape">Grape</b-form-checkbox>
            </b-form-checkbox-group>
        </b-form-group>

        <div>Selected: <strong>{{ selected }}</strong></div>
    </card-component>

    <title-page title="Inline and Stacked checkboxes">
        <p><code>&lt;b-form-checkbox-group&gt;</code> components render inline checkboxes by default, while <code>&lt;b-form-checkbox&gt;</code>
            renders block-level (stacked) checkboxes.</p>
    </title-page>

    <card-component>
        <b-form-group label="Form-checkbox-group inline checkboxes (default)">
            <b-form-checkbox-group v-model="selected2"
                :options="options2"
                name="flavour-1a" />
        </b-form-group>

        <b-form-group label="Form-checkbox-group stacked checkboxes">
            <b-form-checkbox-group v-model="selected2"
                :options="options2"
                name="flavour-2a"
                stacked />
        </b-form-group>

        <b-form-group label="Individual stacked checkboxes (default)">
            <b-form-checkbox v-for="option in options2"
                v-model="selected2"
                :key="option.value"
                :value="option.value"
                name="flavour-3a">
                {{ option.text }}
            </b-form-checkbox>
        </b-form-group>

        <b-form-group label="Individual inline checkboxes">
            <b-form-checkbox v-for="option in options2"
                v-model="selected2"
                :key="option.value"
                :value="option.value"
                name="flavour-4a"
                inline>
                {{ option.text }}
            </b-form-checkbox>
        </b-form-group>
    </card-component>

    <title-page title="Individual checkbox button style">
        <p>A single checkbox can be rendered with a button appearance by setting the prop <code>button</code> to <code>true</code></p>
    </title-page>

    <card-component>
        <b-form-checkbox v-model="checked1"
            name="check-button"
            button>
            Button Checkbox <b>(Checked: {{ checked1 }})</b>
        </b-form-checkbox>
        <b-form-checkbox v-model="checked2"
            name="check-button"
            button
            button-variant="info">
            Button Checkbox <b>(Checked: {{ checked2 }})</b>
        </b-form-checkbox>
    </card-component>

    <title-page title="Grouped button style checkboxes">
        <p>Render groups of checkboxes with the look of a button-group by setting the prop <code>buttons</code> on
            <code>&lt;b-form-checkbox-group&gt;</code>. Change the button variant by setting the <code>button-variant</code> prop to one of
            the standard Bootstrap button variants (see <a href="/docs/components/button"><code>&lt;b-button&gt;</code></a> for supported
            variants). The default <code>button-variant</code> is <code>secondary</code>.</p>
    </title-page>

    <card-component>
        <b-form-group label="Button-group style checkboxes">
            <b-form-checkbox-group v-model="selected3"
                :options="options3"
                name="buttons-1"
                buttons />
        </b-form-group>

        <b-form-group label="Button-group style checkboxes with variant primary and large buttons">
            <b-form-checkbox-group v-model="selected3"
                :options="options3"
                buttons
                button-variant="primary"
                size="lg"
                name="buttons-2" />
        </b-form-group>

        <b-form-group label="Stacked (vertical) button-group style checkboxes">
            <b-form-checkbox-group v-model="selected3"
                :options="options3"
                stacked
                buttons />
        </b-form-group>
    </card-component>

    <title-page title="Individual checkbox switch style">
        <p>A single checkbox can be rendered with a switch appearance by setting the prop <code>switch</code> to <code>true</code></p>
    </title-page>

    <card-component>
        <b-form-checkbox v-model="checked"
            name="check-button"
            switch>
            Switch Checkbox <b>(Checked: {{ checked }})</b>
        </b-form-checkbox>
    </card-component>

    <title-page title="Grouped switch style checkboxes">
        <p>Render groups of checkboxes with the look of a switches by setting the prop <code>switches</code> on
            <code>&lt;b-form-checkbox-group&gt;</code>.</p>
    </title-page>

    <card-component>
        <b-form-group label="Inline switch style checkboxes">
            <b-form-checkbox-group v-model="selected4"
                :options="options4"
                switches />
        </b-form-group>

        <b-form-group label="Stacked (vertical) switch style checkboxes">
            <b-form-checkbox-group v-model="selected4"
                :options="options4"
                switches
                stacked />
        </b-form-group>

    </card-component>

    <title-page title="Non custom check inputs (plain)">
        <p>You can have <code>&lt;b-form-checkbox-group&gt;</code> or <code>&lt;b-form-checkbox&gt;</code> render a browser native checkbox input
            by setting the <code>plain</code> prop.</p>
    </title-page>

    <card-component>
        <b-form-group label="Plain inline checkboxes">
            <b-form-checkbox-group v-model="selected5"
                :options="options5"
                plain />
        </b-form-group>

        <b-form-group label="Plain stacked checkboxes">
            <b-form-checkbox-group v-model="selected5"
                :options="options5"
                plain
                stacked />
        </b-form-group>
    </card-component>

    <title-page title="Contextual state and validation example">
        <p>Bootstrap includes validation styles for <code>valid</code> and <code>invalid</code> states on most form controls.</p>
        <p>To apply one of the contextual state icons on <code>&lt;b-form-checkbox&gt;</code>, set the <code>state</code> prop to
            <code>'invalid'</code> (or <code>false</code>), <code>'valid'</code> (or <code>true</code>), or <code>null</code>.</p>
    </title-page>

    <card-component>
        <b-form-checkbox-group v-model="value6"
            :options="options6"
            :state="state"
            name="checkbox-validation">
            <b-form-invalid-feedback :state="state">Please select two</b-form-invalid-feedback>
            <b-form-valid-feedback :state="state">Thank you</b-form-valid-feedback>
        </b-form-checkbox-group>
    </card-component>

    <title-page title="Single Indeterminate checkbox">
        <p>Normally a checkbox input can only have two states: <em>checked</em> or <em>unchecked</em>. They can have any
            value, but they either submit that value (<em>checked</em>) or don't (<em>unchecked</em>) with a form submission
            (although BootstrapVue allows a value for the <em>unchecked</em> state on a single checkbox)</p>
    </title-page>

    <card-component>
        <b-form-checkbox v-model="checked"
            :indeterminate.sync="indeterminate">
            Click me to see what happens
        </b-form-checkbox>

        <div class="mt-3">
            Checked: <strong>{{ checked }}</strong><br>
            Indeterminate: <strong>{{ indeterminate }}</strong>
            </br></div>

        <b-button @click="toggleIndeterminate">Toggle Indeterminate State</b-button>
    </card-component>
</div>
</template>
<script>
import TitlePage from '@/components/Base/Title/TitlePage'
import TitleTop from '@/components/Base/Title/TitleTop'
import CardComponent from '@/components/Base/Card/CardComponent'

export default {
  components: {
    TitlePage,
    TitleTop,
    CardComponent
  },
  layout: 'admin',
  meta: {
    component: {
      tag: 'b-form-checkbox',
      bsLink: 'https://bootstrap-vue.js.org/docs/components/form-checkbox/#component-reference'
    }
  },
  computed: {
    state () {
      return this.value6.length === 2
    }

  },
  methods: {
    toggleIndeterminate () {
      this.indeterminate = !this.indeterminate
    }

  },

  data () {
    return {
      status: 'not_accepted',
      selected: [],
      // Must be an array reference!
      checked: false,
      checked1: false,
      checked2: false,
      indeterminate: true,
      options: [{
        text: 'Orange',
        value: 'orange'
      }, {
        text: 'Apple',
        value: 'apple'
      }, {
        text: 'Pineapple',
        value: 'pineapple'
      }, {
        text: 'Grape',
        value: 'grape'
      }],
      selected2: [],
      // Must be an array reference!
      selected3: [],
      // Must be an array reference!
      options3: [{
        text: 'Orange',
        value: 'orange'
      }, {
        text: 'Apple',
        value: 'apple'
      }, {
        text: 'Pineapple',
        value: 'pineapple'
      }, {
        text: 'Grape',
        value: 'grape'
      }],
      options2: [{
        text: 'Orange',
        value: 'orange'
      }, {
        text: 'Apple',
        value: 'apple'
      }, {
        text: 'Pineapple',
        value: 'pineapple'
      }, {
        text: 'Grape',
        value: 'grape'
      }],
      selected4: [],
      // Must be an array reference!
      options4: [{
        text: 'Red',
        value: 'red'
      }, {
        text: 'Green',
        value: 'green'
      }, {
        text: 'Yellow (disabled)',
        value: 'yellow',
        disabled: true
      }, {
        text: 'Blue',
        value: 'blue'
      }],
      selected5: [],
      // Must be an array reference!
      options5: [{
        text: 'Orange',
        value: 'orange'
      }, {
        text: 'Apple',
        value: 'apple'
      }, {
        text: 'Pineapple',
        value: 'pineapple'
      }, {
        text: 'Grape',
        value: 'grape'
      }],
      value6: [],
      options6: [{
        text: 'First Check',
        value: 'first'
      }, {
        text: 'Second Check',
        value: 'second'
      }, {
        text: 'Third Check',
        value: 'third'
      }]
    }
  }

}

</script>



